### Variables
@urlLocal = http://localhost:3000/olx
@contentType = application/json

### Show all from mae-luiza 
GET {{urlLocal}}/nova-descoberta

### Get all from mae-luiza (show and persist on mongo)
GET {{urlLocal}}/scraping/nova-descoberta

### Get all from all
GET {{urlLocal}}/scrapingall


### Get informations from a property
GET {{urlLocal}}/properties?url=https://rn.olx.com.br/rio-grande-do-norte/imoveis/rs-vende-se-casa-em-condominio-1345481883

